# Use custom format
format = """
$directory\
$git_branch\
$character"""

# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[🤘](bold fg:6)"
error_symbol = "[🤘](bold fg:6)"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold italic fg:208"

